CREATE TABLE IF NOT EXISTS Groups (
	Name VARCHAR(32) NOT NULL,
	Notecount INT DEFAULT 0,

	PRIMARY KEY(Name)
);

CREATE TABLE IF NOT EXISTS Notes (
	ID INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(32) NOT NULL,
	GroupName VARCHAR(32),
	Content VARCHAR(256),
	Creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	LastModify TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	
	PRIMARY KEY (ID), 
	FOREIGN KEY(GroupName) REFERENCES Groups (Name)
);
