CREATE TABLE IF NOT EXISTS Notes {
	ID INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(32) NOT NULL,
	GroupID INT,
	Content VARCHAR(256),
	Creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	LastModify TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	
	PRIMARY KEY (ID), 
	FOREIGN KEY(GroupID) REFERENCES Groups (ID)
};

CREATE TABLE IF NOT EXISTS Groups {
	ID INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(32) NOT NULL,

	PRIMARY KEY(ID)
};

